name: unittests
on: push

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.16'
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.1
      - name: Install Dependencies
        run: poetry install --no-root

      - name: Run Tests
        run: poetry run python -m unittest
